### ISSUE TITLE
Add Navbar with animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#1]
The basic layout can be seen in the screenshot.
Check out this link to see the animation https://technorax-v6.tech/
![ss1](https://user-images.githubusercontent.com/63084088/95383589-0220ed00-0909-11eb-8644-93c853a2336f.PNG)

Do attach screen recordings/screenshots😀

**Comment by Amulya-coder** [comment]
@sumana2001 in this what type of animation you want simple hover effect or any type of active tab animation when you hover on it.

**Comment by sumana2001** [comment]
@Amulya-coder You can refer to this link. The navbar here and its animation is what I'm looking for.
https://technorax-v6.tech/
Hope it helps😀
