### ISSUE TITLE
Photo timeline

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#10]
Check out the animation here at 1:26 https://www.youtube.com/watch?v=MaCDTGw4o2s

![ss9](https://user-images.githubusercontent.com/63084088/95440277-61691680-0976-11eb-9d65-04fc9da9311c.PNG)

Do attach screen recordings/screenshots😀

**Comment by SharadaSowmya14** [comment]
Hey @sumana2001! I want to work on this. Could you please assign it to me?

**Comment by sumana2001** [comment]
Sure! Go ahead😀
