### ISSUE TITLE
Responsive Text Timeline

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#11]
Check out the animation here at 0:22 https://www.youtube.com/watch?v=MaCDTGw4o2s

![ss8](https://user-images.githubusercontent.com/63084088/95440463-98d7c300-0976-11eb-9052-2fccc1261a82.PNG)

Do attach screen recordings/screenshots😀

**Comment by Dhamodhar-DDR** [comment]
I'd like to work on it !

**Comment by SharadaSowmya14** [comment]
Hi! I have added a PR with the implementation of Responsive Tesxt timeline. 
[https://github.com/sumana2001/styles/pull/15](url)
Could you please have a look and let me know if this is what you were looking for?
And also It would great if you could assign this issue to me!
