### ISSUE TITLE
Menu Hover Effect

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#12]
Check out the animation here at 0:41 https://www.youtube.com/watch?v=lnFfsP5EKf8&t=93s

![ss10](https://user-images.githubusercontent.com/63084088/95442841-7f844600-0979-11eb-9883-a8c7578abae6.PNG)

Do attach screen recordings/screenshots😀

**Comment by Dhamodhar-DDR** [comment]
I'd like to work on it.

**Comment by sumana2001** [comment]
Sure! Go ahead😀 @Dhamodhar-DDR
