### ISSUE TITLE
Liquid Preloader

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#24]
Check out the animation here at 1:48 https://www.youtube.com/watch?v=pvrLk8gPvN8&t=37s

![ss](https://user-images.githubusercontent.com/63084088/95536767-717e0600-0a09-11eb-9066-f1d3de0744eb.PNG)

Do attach screen recordings/screenshots😀

**Comment by SharadaSowmya14** [comment]
Hey @sumana2001 I want to work on this. Could you please assign it to me?

**Comment by sumana2001** [comment]
Sure! Go ahead😄
