### ISSUE TITLE
Image Slider with animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#25]
Check out the animation here at 0:37 https://www.youtube.com/watch?v=bqfOALK0qnc

![ss1](https://user-images.githubusercontent.com/63084088/95537067-4e078b00-0a0a-11eb-907b-b4976276f116.PNG)

Do attach screen recordings/screenshots😀

**Comment by KeshriAyushi22** [comment]
Hi, It would be exactly same? Can you assign me this, it will be great learning experience

**Comment by geeks5551** [comment]
hey can i work on this issue?

**Comment by sumana2001** [comment]
@KeshriAyushi22 Sure! Go ahead!😄 It should be the same animation. you can change the styling and pictures if you want

**Comment by himanshubobade** [comment]
@sumana2001 Can I contribute and solve this issue??

**Comment by sumana2001** [comment]
@himanshubobade Sure go ahead😄

**Comment by himanshubobade** [comment]
@sumana2001 I have completed the task and created a pull request.. Thankyou :)
