### ISSUE TITLE
Mini Carousel

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#26]
Check out the animation here at 1:48

![ss2](https://user-images.githubusercontent.com/63084088/95537277-ebfb5580-0a0a-11eb-9217-09213cf3719f.PNG)
 https://www.youtube.com/watch?v=bqfOALK0qnc

Do attach screen recordings/screenshots😀

**Comment by prsa2511** [comment]
Hi, can you assign this issue to me so I can start working on it.

**Comment by sumana2001** [comment]
Sure! Go ahead😀 @prsa2511

**Comment by prsa2511** [comment]
I've submitted the pull request. Do tell if any changes are required!
