### ISSUE TITLE
3D Carousel

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#27]
Check out the animation here at 2:04 https://www.youtube.com/watch?v=bqfOALK0qnc

![ss3](https://user-images.githubusercontent.com/63084088/95537375-31b81e00-0a0b-11eb-8314-b08d61a77ab3.PNG)

Do attach screen recordings/screenshots😀

**Comment by greg95000** [comment]
Hello,
Can I take this ticket pls?

**Comment by geeks5551** [comment]
hey can i work on this issue?

**Comment by sumana2001** [comment]
@greg95000 Sure! Go ahead😄

**Comment by pablowbk** [comment]
if possible, would like to contribute to this one, too

**Comment by greg95000** [comment]
Sure I don't had the time to do it so @sumana2001 can you assign him pls? 
Sorry for the inconvenient

**Comment by sumana2001** [comment]
@greg95000 Okay no issues

**Comment by sumana2001** [comment]
@pablowbk Go ahead😄
