### ISSUE TITLE
3D Isometric Social Media Icons

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#28]
Check out the animation here at 1:14 https://www.youtube.com/watch?v=d5IOejA9rx0

![ss4](https://user-images.githubusercontent.com/63084088/95538649-d9cde700-0a0b-11eb-8c2a-1eca30ecbc78.PNG)

Do attach screen recordings/screenshots😀

**Comment by Amulya-coder** [comment]
Hey @sumana2001 I want to work on this. Kindly Assign it.

**Comment by sumana2001** [comment]
Sure! go ahead😄

**Comment by sumana2001** [comment]
@Amulya-coder Since you haven't sent the pr yet, I am unassigning it.😊
