### ISSUE TITLE
Glowing Loading Page

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#29]
Check out the animation here at 3:18 https://www.youtube.com/watch?v=d5IOejA9rx0

![ss5](https://user-images.githubusercontent.com/63084088/95539513-36310680-0a0c-11eb-93df-e8f413ba94d4.PNG)

Do attach screen recordings/screenshots😀

**Comment by orama254** [comment]
Greetings
I'd like to contribute to this issue...do you want an exact replica of the animation or are there specifics to focus on?

**Comment by sumana2001** [comment]
Sure! Go ahead😀 @orama254 
The animation should be similar to this. A few small changes are fine .
