### ISSUE TITLE
Add Product Card UI Design

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#3]
Check out the animation here at 0:46 https://www.youtube.com/watch?v=QNTeq4QdOsQ&t=1s
![ss3](https://user-images.githubusercontent.com/63084088/95383996-9ee38a80-0909-11eb-9507-f2cc7992b0f9.PNG)

Do attach screen recordings/screenshots😀

**Comment by Aldhanekaa** [comment]
Can you please explain what we have to do?

**Comment by sumana2001** [comment]
You can check out the animation in the youtube link given and make anything similar to it
Happy coding!😀

**Comment by Aldhanekaa** [comment]
so may I work on this issue?

**Comment by sumana2001** [comment]
Sure! Go ahead @Aldhanekaa 😃
