### ISSUE TITLE
Responsive Cards

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#30]
Check out the cards here at 5:13 https://www.youtube.com/watch?v=d5IOejA9rx0

![ss6](https://user-images.githubusercontent.com/63084088/95539685-a8095000-0a0c-11eb-9dc1-cbf1dc118bf8.PNG)

Do attach screen recordings/screenshots😀

**Comment by Amulya-coder** [comment]
@sumana2001 I want to work on this. Kindly Assign it.

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by iamrishavraj1** [comment]
Hello Mam, Can You Please Assign me this issue.

**Comment by RamanaVem** [comment]
hey can i take a look on this?
