### ISSUE TITLE
SVG Wave Banner

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#31]
Check out the banner here at 5:24 https://www.youtube.com/watch?v=d5IOejA9rx0

![ss7](https://user-images.githubusercontent.com/63084088/95539815-fd456180-0a0c-11eb-89bc-5c66ee4d1878.PNG)

Do attach screen recordings/screenshots😀

**Comment by MeghalBisht** [comment]
Please elaborate

**Comment by MeghalBisht** [comment]
Can i take this?

**Comment by geeks5551** [comment]
hey can i contribute to this issue?

**Comment by sumana2001** [comment]
@MeghalBisht Sure go ahead😄

**Comment by sumana2001** [comment]
@geeks5551 Sorry you can try some other issue or create your own issue if you want to add a special effect. Once you create the issue I'll assign it to you.
