### ISSUE TITLE
Wavy Div Animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#32]
Check out the animation here at 0:53 https://www.youtube.com/watch?v=bbHuo22R34I

![ss8](https://user-images.githubusercontent.com/63084088/95540069-a68c5780-0a0d-11eb-9058-5da2f917c18d.PNG)

Do attach screen recordings/screenshots😀

**Comment by thelavenderhue** [comment]
@sumana2001 can I work on this?

**Comment by sumana2001** [comment]
@thelavenderhue Sure! Go ahead😁
