### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#33]
Check out the animation here at 0:09 https://www.youtube.com/watch?v=6HFpw5fcaD8

![ss9](https://user-images.githubusercontent.com/63084088/95540390-4d70f380-0a0e-11eb-94f5-dff5fdeac47c.PNG)

Do attach screen recordings/screenshots😀

**Comment by bineetNaidu** [comment]
I am looking forward to work in it , if you allow me, please assign me this task

**Comment by sumana2001** [comment]
Sure! Go ahead😀 @bineetNaidu

**Comment by bineetNaidu** [comment]
> Sure! Go ahead @bineetNaidu

I have a question that in which folder does the project lies?

**Comment by sumana2001** [comment]
@bineetNaidu You need to create a separate folder for the sticky navbar

**Comment by bineetNaidu** [comment]
> @bineetNaidu You need to create a separate folder for the sticky navbar

Ok thanks for the help :smile:
