### ISSUE TITLE
Responsive Masonry Layout 

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#4]
Check out the animation here at 1:36 https://www.youtube.com/watch?v=QNTeq4QdOsQ&t=1s
![ss4](https://user-images.githubusercontent.com/63084088/95384154-d18d8300-0909-11eb-8909-d2cef0c6b78a.PNG)

Do attach screen recordings/screenshots😀

**Comment by anushri20** [comment]
Hi, Can I work on this?

**Comment by sumana2001** [comment]
Sure! Go ahead😀 @anushri20

**Comment by pablowbk** [comment]
would like to contribute to this one.

**Comment by sumana2001** [comment]
Sure @pablowbk . I'll assign this to you as well as @anushri20 has not responded yet

**Comment by pablowbk** [comment]
pr submitted
