### ISSUE TITLE
Animated Leaves Effect

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#45]
Check out the animation here at 0:24 https://www.youtube.com/watch?v=KYOYVZcZYAI

![ss1](https://user-images.githubusercontent.com/63084088/95681056-5a9f0580-0bfb-11eb-8677-feac3ccfe065.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
can i work on this?

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by pratyushakatti13** [comment]
hey, can i work on this?

**Comment by sumana2001** [comment]
Yes. Go ahead! @pratyushakatti13
