### ISSUE TITLE
Ripple effect on Icon Hover

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#46]
Check out the animation here at 0:39 https://www.youtube.com/watch?v=KYOYVZcZYAI

![ss2](https://user-images.githubusercontent.com/63084088/95681169-021c3800-0bfc-11eb-8344-93156bc496cd.PNG)

Do attach screen recordings/screenshots😀

**Comment by danisoc** [comment]
Can I give this a try?

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by danisoc** [comment]
#54
