### ISSUE TITLE
Button Animated Background

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#47]
Check out the animation here at 0:54 https://www.youtube.com/watch?v=KYOYVZcZYAI

![ss3](https://user-images.githubusercontent.com/63084088/95681234-50313b80-0bfc-11eb-9734-bcd4d4dc70e6.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
hey can i work on this issue @sumana2001

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by jahnavi1111** [comment]
Hey!
I would like to work on it @sumana2001
