### ISSUE TITLE
List animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#48]
Check out the animation here at 1:24 https://www.youtube.com/watch?v=KYOYVZcZYAI

![ss4](https://user-images.githubusercontent.com/63084088/95681286-8969ab80-0bfc-11eb-8615-56ee386f31f8.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
hey can i work on this issue @sumana2001

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by chaitrahanchinal0612** [comment]
Do you want this effect to be added to the MenuHoverEffect folder?

**Comment by chaitrahanchinal0612** [comment]
@sumana2001 can you please check PR#63

**Comment by sumana2001** [comment]
@geeks5551 Since you haven't replied since five days I'm reassigning your issues. Sorry. 
Happy coding!

**Comment by sumana2001** [comment]
@chaitrahanchinal0612 Sorry for not replying earlier, I need the list animation is a separate folder and not mixed with another one. Hope this helps.😄

**Comment by chaitrahanchinal0612** [comment]
@sumana2001 I have made a new pull request with a separate folder, can u please check that.
