### ISSUE TITLE
Navbar in pieces animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#49]
Check out the animation here at 0:00 https://www.youtube.com/watch?v=kAGkAJDLYGY

![ss5](https://user-images.githubusercontent.com/63084088/95681312-b453ff80-0bfc-11eb-936d-2039603301aa.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
hey can i work on this issue @sumana2001

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by jahnavi1111** [comment]
Hey!
I would like to work on this @sumana2001
