### ISSUE TITLE
Card UI Design with hover effects

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#5]
Check out the animation here at 2:44 https://www.youtube.com/watch?v=QNTeq4QdOsQ&t=1s

![ss5](https://user-images.githubusercontent.com/63084088/95384414-377a0a80-090a-11eb-9043-fae633f425fb.PNG)

Do attach screen recordings/screenshots😀

**Comment by thelavenderhue** [comment]
@sumana2001  can I work on this?

**Comment by sumana2001** [comment]
@mrinal-27 Sure! Go ahead😀

**Comment by thelavenderhue** [comment]
Thank you @sumana2001. 
Do I have to create the exact card and hover effect or can I add something of my own?

**Comment by sumana2001** [comment]
@mrinal-27 You have to create something similar. But if you want to add some other effect you can create another issue and solve it. It would be great if you do so😁

**Comment by thelavenderhue** [comment]
@sumana2001 okay I'm on it.

**Comment by thelavenderhue** [comment]
@sumana2001 please let me know if you would like any changes

**Comment by mishrashree18** [comment]
I want to work on this, can I ?

**Comment by sumana2001** [comment]
@mishrashree18 Sorry it's already done. You can try the other issues or create an issue here and solve it.
Happy coding!😀
