### ISSUE TITLE
Side Navbar animation

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#50]
Check out the animation here at 2:05 https://www.youtube.com/watch?v=kAGkAJDLYGY

![ss6](https://user-images.githubusercontent.com/63084088/95681339-e36a7100-0bfc-11eb-9441-56d3ffae749f.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
hey can i work on this issue @sumana2001

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by Anushree176** [comment]
Hi,
Is the issue still available?
I would like to work on it.

**Comment by sumana2001** [comment]
@Anushree176 Yes go ahead😄

**Comment by Anurag-ak99** [comment]
hey @sumana2001 I would like to contribute to the project.

**Comment by ritviksharma3** [comment]
Hey @sumana2001 ! Is this Issue still available ? If yes please assign it to me, will resolve it ASAP.

**Comment by Anushree176** [comment]
> 
> 
> @Anushree176 Yes go ahead😄

Hey @sumana2001 ! I had created PR #67 . Please review 😄
