### ISSUE TITLE
Diagonal Navbar

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#51]
Check out the animation here at 2:43 https://www.youtube.com/watch?v=kAGkAJDLYGY

![ss7](https://user-images.githubusercontent.com/63084088/95681417-5d9af580-0bfd-11eb-92e0-fa7764bf9a30.PNG)

Do attach screen recordings/screenshots😀

**Comment by MeghalBisht** [comment]
Can i go for this?

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by MeghalBisht** [comment]
Thanks its done!
