### ISSUE TITLE
Particles on Navbar

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#52]
Check out the animation here at 5:20 https://www.youtube.com/watch?v=kAGkAJDLYGY

![ss8](https://user-images.githubusercontent.com/63084088/95681556-119c8080-0bfe-11eb-947e-e14399fbdd5a.PNG)

Do attach screen recordings/screenshots😀

**Comment by geeks5551** [comment]
hey can i work on this issue @sumana2001

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by Aldhanekaa** [comment]
> hey can i work on this issue @sumana2001

wow I found you everywhere

**Comment by priyanshi0799** [comment]
hey, can you assign this issue to me?
I'll try to resolve it ASAP 😄

**Comment by sumana2001** [comment]
Sure go ahead😄 @priyanshi0799

**Comment by himanshubobade** [comment]
hey can you assign me this?? @sumana2001

**Comment by sumana2001** [comment]
Sure I'll assign it to you as well😄 @himanshubobade

**Comment by himanshubobade** [comment]
@sumana2001 I have created a pull request please check it out once.. Thank you so much for the opportunity
