### ISSUE TITLE
Circular Navigation

### ISSUE THREAD

**Issue by MeghalBisht** [sumana2001/styles#58]
![2020-10-12 (7)](https://user-images.githubusercontent.com/61330148/95758952-b71b2700-0cc6-11eb-875c-0cf6dec34d19.png)

**Comment by iamrishavraj1** [comment]
Hello Mam, Can You Please Assign me This issue..

**Comment by MeghalBisht** [comment]
Hi @iamrishavraj1, I am already working on it since I opened it.
Thanks
