### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#6]
Check out the animation here at 0:30 https://www.youtube.com/watch?v=9Bl8szMyfhU

![ss6](https://user-images.githubusercontent.com/63084088/95384905-e4ed1e00-090a-11eb-98f4-165f5ec04cb8.PNG)

Do attach screen recordings/screenshots😀

**Comment by SharadaSowmya14** [comment]
Hey @sumana2001 I want to work on this. Could you please assign it to me?

**Comment by sumana2001** [comment]
Sure! Go ahead😀
