### ISSUE TITLE
Button Ripple effect

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/styles#9]
Create a button which when clicked will show a ripple effect somewhat like this:

![ss7](https://user-images.githubusercontent.com/63084088/95435610-6aef8000-0970-11eb-9d2c-c00e6dd66b7e.PNG)

Do attach screen recordings/screenshots😀

**Comment by Amulya-coder** [comment]
Hey @sumana2001  I want to work on it. Kindly Assign it. Can You tell me more about it. Where I have to add this button.

**Comment by sumana2001** [comment]
Sure! @Amulya-coder 
This repo is just a collection of effects so you can create a button in a separate html file to display the effect
Happy coding!😀

**Comment by mishrashree18** [comment]
Hi @sumana2001 , I want to work on this. Can you please assign it to me?

**Comment by Amulya-coder** [comment]
@sumana2001 How was it looks
![image](https://user-images.githubusercontent.com/66437295/95476374-cf2c3700-09a4-11eb-8659-8641b2d4789f.png)
